# Site settings
title: Arturo V
email: kuatroestrellas@gmail.com
url: https://kuatroestrellas.github.io
description: "Arturo Vargas Gutierrez"
keywords: "pagina personal, "
skills: "Ing en TICs - MAKER - Freelancer"
meta_author: Arturo Vargas Gutierrez

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: kuatroestrellas
  location: visitas
  social: Sigueme
  credits: Apoyo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/kuatroestrellas
  - title: facebook
    url: https://facebook.com/kuatroestrellas1
  - title: linkedin
    url: https://www.linkedin.com/in/kuatroestrellas/
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/kuatroestrellas
  - title: youtube
    url: https://www.youtube.com/channel/UC6z6CXj2bMN1tcSGvHZJYCw

# Postal address (add as many lines as necessary)
address:
#  - line: Mi primer libro
  - line: <center><img src="https://www.cerotec.net/contador.php?t=5&s=3&i=127902"> </center>
  #- line: https://www.cerotec.net/estadisticas-127902/kuatroestrellas.github.io

# Credits content
credits: '<a href="https://www.buymeacoffee.com/kuatroestrellas" target="_blank"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" alt="Buy Me A Coffee" style="height: auto !important;width: auto !important;" ></a><br>o<br><a target=_blank href=https://www.paypal.me/kuatroestrellas/10><img src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" /></a><br>¡Gracias!'
#'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
